Changed some css
SDarkMagic/Relics-Website pull request #1
Opened 2020-12-18 15:54 UTC by S41L0R

I changed some css on the download page and the navbar. The navbar changes look pretty bad, they might look better if the triangles were bigger. Idk what to do for that because of some weird tiling issues.

2020-12-20 00:27 UTC, SDarkMagic requested changes
CSS changes and package-lock updates are good, not so sure about the image ones

2020-12-22 14:50 UTC, S41L0R commented
yeah the main issue with the image ones were I need the triangles to be bigger, but it creates tiling issues. I'll update this pull request to not include the images.

2020-12-22 14:55 UTC, S41L0R commented
Ok, I've removed the image changes

2020-12-22 16:19 UTC, SDarkMagic approved these changes

2020-12-22 16:20 UTC, merged